<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class DataPage extends Model
{
    use HasFactory;

    protected $fillable = [
        "title",
        "header_nav_1",
        "header_nav_2",
        "header_nav_3",
        "block_1_title",
        "block_1_title_marked",
        "block_1_title_2",
        "block_1_description",
        "block_1_button_text",
        "block_1_button_link",
        "block_2_nav_1",
        "block_2_nav_2",
        "block_2_nav_3",
        "block_2_nav_4",
        "block_2_nav_icon_1",
        "block_2_nav_icon_2",
        "block_2_nav_icon_3",
        "block_2_nav_icon_4",
        "block_3_title",
        "block_3_title_marked",
        "block_3_decription",
        "block_3_static_procent_1",
        "block_3_static_procent_text_1",
        "block_3_static_procent_2",
        "block_3_static_procent_text_2",
        "block_3_static_procent_3",
        "block_3_static_procent_text_3",
        "block_3_static_procent_4",
        "block_3_static_procent_text_4",
        "block_3_text_under_video",
        "block_4_title",
        "block_4_description",
        "block_5_title_marked",
        "block_5_title",
        "block_5_description",
        "block_5_button_text",
        "block_5_button_link",
        "block_5_step1_title",
        "block_5_step1_description",
        "block_5_step2_title",
        "block_5_step2_description",
        "block_5_step3_title",
        "block_5_step3_description",
        "block_6_title",
        "block_6_title_marked",
        "block_6_description",
        "block_7_title_marked",
        "block_7_title",
        "block_7_description",
        "block_8_element_title_1",
        "block_8_element_description_1",
        "block_8_element_title_2",
        "block_8_element_description_2",
        "block_8_element_title_3",
        "block_8_element_description_3",
        "block_8_element_title_4",
        "block_8_element_description_4",
        "block_8_element_title_5",
        "block_8_element_description_5",
        "block_8_element_title_6",
        "block_8_element_description_6",
        "block_9_title",
        "block_9_description",
        "block_9_button_text",
        "block_9_button_link",
        "block_10_title",
        "block_10_static_1",
        "block_10_static_1_description",
        "block_10_static_2",
        "block_10_static_2_description",
        "block_10_static_3",
        "block_10_static_3_description",
        "block_11_reviews",
        "block_12_title",
        "block_12_button_text",
        "block_12_button_link",
        "footer_tg_link",
        "footer_email",
        "footer_other_text",
    ];


}
